version: "3.8"
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/code/staticfiles

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata:
  static_volume:
  caddy_data:
  caddy_config:
