services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    # bind-mount the app dir so code edits update immediately (works for local & VPS)
    volumes:
      - ./app:/code:delegated
      - static_volume:/code/staticfiles
    # expose internal port only; Caddy reverse-proxies to it
    ports:
      - "8000:8000"                 # optional for local testing; can be left or removed on VPS
    restart: unless-stopped

  db:
    image: postgres:15
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  caddy:
    image: caddy:2
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    # give Caddy access to the Caddyfile and to the static volume
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - static_volume:/code/staticfiles:ro
    environment:
      - DOMAIN=${DOMAIN}   # ensures {$DOMAIN} inside Caddyfile is substituted

volumes:
  pgdata:
  static_volume:
  caddy_data:
  caddy_config:
