services:
  web:
    build: .
    env_file:
    - .env
    depends_on:
    - db
    volumes:
    - ./app:/code:delegated
    - static_volume:/code/staticfiles
    - media_volume:/code/media
    ports:
    - 8000:8000
    restart: unless-stopped
    environment:
    - DJANGO_SETTINGS_MODULE=config.settings.production
  db:
    image: postgres:15
    env_file:
    - .env
    restart: unless-stopped
    volumes:
    - pgdata:/var/lib/postgresql/data
  caddy:
    image: caddy:2
    env_file:
    - .env
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    - caddy_data:/data
    - caddy_config:/config
    - static_volume:/code/staticfiles:ro
    environment:
    - DOMAIN=${DOMAIN}
volumes:
  pgdata: null
  static_volume: null
  caddy_data: null
  caddy_config: null
  media_volume: null
