services:
  web:
    build: .
    volumes:
      - ./app:/code
      - static_volume:/code/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - WAIT_FOR_DB=1
      - PYTHONPATH=/code
    # no explicit command needed because ENTRYPOINT will exec "$CMD" (gunicorn from Dockerfile)
