# Generated by Django 5.2.6 on 2025-09-20 05:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=128, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ('party_code',),
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('product_group', models.CharField(choices=[('FG', 'Finished Good'), ('RM', 'Raw Material'), ('WIP', 'Work in Progress'), ('TRM1', 'Trims BOM Excl'), ('TRM0', 'Trims BOM Incl')], default='RM', max_length=10)),
                ('style_group', models.CharField(blank=True, default='', help_text='Optional: style group / collection', max_length=128)),
                ('shade', models.CharField(blank=True, default='', max_length=60)),
                ('size', models.CharField(blank=True, default='', max_length=30)),
                ('uom', models.CharField(blank=True, default='pcs', max_length=20)),
                ('standard_cost', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BOMHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Governance state of this BOM', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('total_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('immutable_snapshot', models.JSONField(blank=True, help_text='Optional read-only snapshot stored on approve/activate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('product_plant', 'version'),
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='masters.plant')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'ordering': ('plant__code', 'code'),
                'unique_together': {('plant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ProductPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('is_fg', models.BooleanField(blank=True, help_text='Denormalized: is this a Finished Good (FG)?', null=True)),
                ('product_type_code', models.IntegerField(blank=True, help_text='Small int code for product type/group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productplants', to='masters.plant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productplants', to='masters.product')),
            ],
            options={
                'verbose_name': 'Product - Plant',
                'verbose_name_plural': 'Products - Plants',
                'ordering': ('product__code', 'plant__code'),
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extended_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='masters.bomheader')),
                ('component', models.ForeignKey(help_text='Component as plant-specific product (ProductPlant)', on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='masters.productplant')),
            ],
            options={
                'verbose_name': 'BOM Item',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='bomheader',
            name='product_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='masters.productplant'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_plant_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_to_user', models.DateTimeField(blank=True, help_text='When profile last pushed changes to User', null=True)),
                ('last_synced_from_user', models.DateTimeField(blank=True, help_text='When profile last pulled changes from User', null=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='masters.plant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='masters.plant')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='masters.productionline')),
            ],
            options={
                'verbose_name': 'Worker',
                'ordering': ('plant__code', 'code'),
            },
        ),
        migrations.AddIndex(
            model_name='productplant',
            index=models.Index(fields=['plant_id', 'is_fg'], name='masters_pp_plant_isfg_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productplant',
            unique_together={('product', 'plant')},
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(fields=('bom', 'component'), name='masters_bomitem_bom_component_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bomheader',
            constraint=models.UniqueConstraint(fields=('product_plant', 'version'), name='masters_bomheader_pp_version_uniq'),
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('plant', 'code')},
        ),
    ]
