# Generated by Django 5.2.6 on 2025-09-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style_group',
            field=models.CharField(blank=True, default='', help_text='Optional: style group / collection', max_length=128),
        ),
    ]
