# Generated by Django 5.2.6 on 2025-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_add_style_group_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(choices=[('FG', 'Finished Good'), ('RM', 'Raw Material'), ('WIP', 'Work in Progress'), ('TRM', 'Trims BOM Excl')], default='RM', max_length=10),
        ),
    ]
