# Generated by Django 5.2.6 on 2025-09-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_add_created_by_to_productplant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productplant',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group',
            field=models.CharField(choices=[('FG', 'Finished Good'), ('RM', 'Raw Material'), ('WIP', 'Work in Progress'), ('TRM1', 'Trims BOM Excl'), ('TRM0', 'Trims BOM Incl')], default='RM', max_length=10),
        ),
    ]
