# Generated by Django 5.2.6 on 2025-09-15 21:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_add_style_group_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomheader',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='productplant',
            name='standard_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=14),
        ),
    ]
