# Generated by Django 5.2.6 on 2025-09-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_remove_productplant_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productplant',
            options={'ordering': ('product__code', 'plant__code'), 'verbose_name': 'Product - Plant', 'verbose_name_plural': 'Products - Plants'},
        ),
        migrations.RemoveField(
            model_name='productplant',
            name='standard_cost',
        ),
        migrations.AddField(
            model_name='productplant',
            name='is_fg',
            field=models.BooleanField(blank=True, help_text='Denormalized: is this a Finished Good (FG)?', null=True),
        ),
        migrations.AddField(
            model_name='productplant',
            name='product_type_code',
            field=models.IntegerField(blank=True, help_text='Small int code for product type/group', null=True),
        ),
        migrations.AlterField(
            model_name='productplant',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productplant',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productplants', to='masters.plant'),
        ),
        migrations.AlterField(
            model_name='productplant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productplants', to='masters.product'),
        ),
    ]
