# Generated by Django 5.2.6 on 2025-09-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_add_index_productplant_plant_isfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productplant',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='productplant',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
