# Generated by Django 5.2.6 on 2025-09-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_add_bomheader_snapshot_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomheader',
            options={'ordering': ('product_plant', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='bomheader',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bomheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='immutable_snapshot',
            field=models.JSONField(blank=True, help_text='Optional read-only snapshot stored on approve/activate', null=True),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='product_plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='masters.productplant'),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bomheader',
            name='workflow_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Governance state of this BOM', max_length=16),
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='overhead_cost',
        ),
        migrations.RemoveField(
            model_name='bomheader',
            name='scrap_percent',
        ),
    ]
