# Generated by Django 5.2.6 on 2025-09-18 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_bomheader_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='extended_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='bomitem',
            name='unit_cost_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='bomheader',
            constraint=models.UniqueConstraint(fields=('product_plant', 'version'), name='masters_bomheader_pp_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='bomitem',
            constraint=models.UniqueConstraint(fields=('bom', 'component'), name='masters_bomitem_bom_component_uniq'),
        ),
    ]
